--- 
title: "実証分析入門"
author: "長田悠生 (学籍番号: 202310330)"
date: 2023/12/14
format:
    dashboard:
        theme: yeti
        orientation: rows
        logo: images/hello.jpg
        website:
        nav-buttons:
        - icon: github
          href: https://github.com/Myxogastria0808/empirical_analysis_homework1
--- 

```{r}
library(wooldridge)
library(modelsummary)
library(estimatr)
library(gt)
```

# Main

## Row {width=100%}

```{r}
#| title: 元データ (wooldridge packageの wage1)
knitr::kable(wage1)
```

## Row {width=100%}

### Column {width=50%}

```{r}
#| title: 調査対象のデータ (wooldridge packageの wage1の一部)

educ <- wage1$educ
profocc <- wage1$profocc
clerocc <- wage1$clerocc
servocc <- wage1$servocc

edited_wage1 <- data.frame(
    educ, profocc, clerocc, servocc
)

edited_wage1 |>
    gt() |>
        tab_header(title = "wooldridge", subtitle = "edited_wage1")
```

### Column {.tabset}

```{r}
#| title: 重回帰分析の結果

ex1_list <- list(
    "重回帰分析" = lm(educ ~ profocc + clerocc + servocc, data <- wage1)
)

msummary(
    ex1_list,
    stars=TRUE,
    gof_omit = "R2|R2 Adj.|AIC|BIC|Log.Lik.|RMSE",
    fmt="%.4f"
)
```

```{r}
#| title: 標準誤差と頑健標準誤差

ex2_list <- list(
    "Default" = lm(educ ~ profocc + clerocc + servocc, data <- wage1),
    "Robust" = lm_robust(educ ~ profocc + clerocc + servocc, data <- wage1, se_type = "stata")
)

msummary(
    ex2_list,
    stars=TRUE,
    gof_omit = "R2|R2 Adj.|AIC|BIC|Log.Lik.|RMSE",
    fmt="%.4f"
)
```

# Interpretation {orientation="columns" scrolling="true"}


::: {.card}

# それぞれの推定結果の解釈

※ 以下の解釈は、統計を学習し始めた、学生の書いたものであるので、間違っている可能性があります。ご了承ください。

`(Intercept)`と`profocc`と`clerocc`について、優位性を表すデータ内の `*`の数は、p < 0.001を示す個数分ついているので、推定値は統計的に有意であることがわかった。

参考文献

<https://qiita.com/saka212/items/8c74854171775e5d5273>

<https://qiita.com/mendako/items/ed78321bacd04ff4511c>
:::